title: "Toshimaru's blog"
url: "https://toshimaru.net"
baseurl: "/blog"
description: >
  Where there's a will, there's a way.
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Navigation
# nav:
#   - name:           "About"
#     href:           "//kiko.gfjaru.com/about"
#   - name:           "Download"
#     href:           "//github.com/gfjaru/Kiko/releases"
