name: "toshimaru's blog"
baseurl: "/blog"

# Navigation
# nav:
  # - name:           "About"
    # href:           "//kiko.gfjaru.com/about"
  # - name:           "Download"
    # href:           "//github.com/gfjaru/Kiko/releases"

sass:
    style: compressed

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
