title: "Toshimaru's Blog"
url: "https://blog.toshima.ru"
destination: ./docs
description: >
  Where there's a will, there's a way.
sass:
  style: compressed
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-include_sass
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - kramdown-amp
exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
# GitHub Flavored Markdown
kramdown:
  input: GFM

# jekyll-seo
twitter:
  username: toshimaru_e
author:
  name: toshimaru
  twitter: toshimaru_e

jekyll-archives:
  enabled: [year, month, tags]

post_front_matter:
  tags:

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: https://avatars2.githubusercontent.com/u/803398

# Navigation
# nav:
#   - name:           "About"
#     href:           "//kiko.gfjaru.com/about"
#   - name:           "Download"
#     href:           "//github.com/gfjaru/Kiko/releases"
