title: "Toshimaru's Blog"
url: "http://blog.toshima.ru"
description: >
  Where there's a will, there's a way.
sass:
  style: compressed
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- vendor

# GitHub Flavored Markdown
kramdown:
  input: GFM

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Navigation
# nav:
#   - name:           "About"
#     href:           "//kiko.gfjaru.com/about"
#   - name:           "Download"
#     href:           "//github.com/gfjaru/Kiko/releases"
