name: Jekyll
on:
  push:
    branches:
      - master
      - gh-pages-action # TODO: 削除
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('**/Gemfile.lock')}}
        restore-keys: bundler-
    - name: bundle install
      run: |
        bundle config set path 'vendor/bundle'
        bundle install
